"""add_score_breakdown_to_candidate

Revision ID: 19e4a9fb3e33
Revises: 7b755c874cf7
Create Date: 2026-06-26 06:43:55.634302
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '19e4a9fb3e33'
down_revision: Union[str, None] = '7b755c874cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'score_breakdown')
    # ### end Alembic commands ###
