"""Add file_hash to resumes

Revision ID: 1e071c7e3ed8
Revises: c3b244f80035
Create Date: 2026-06-23 10:34:24.708226
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1e071c7e3ed8'
down_revision: Union[str, None] = 'c3b244f80035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_resumes_file_hash'), 'resumes', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_file_hash'), table_name='resumes')
    op.drop_column('resumes', 'file_hash')
    # ### end Alembic commands ###
