"""

Revision ID: 5618884e3aec
Revises: 19e4a9fb3e33
Create Date: 2026-06-26 10:51:54.864628
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5618884e3aec'
down_revision: Union[str, None] = '19e4a9fb3e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
