"""add notes and pipeline_stage to candidates

Revision ID: 7b755c874cf7
Revises: 1e071c7e3ed8
Create Date: 2026-06-24 06:49:00.130550
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7b755c874cf7'
down_revision: Union[str, None] = '1e071c7e3ed8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('candidates', sa.Column('pipeline_stage', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'pipeline_stage')
    op.drop_column('candidates', 'notes')
    # ### end Alembic commands ###
