"""initial

Revision ID: 8eb46ea4e585
Revises: c6fd241b18eb
Create Date: 2026-06-19 09:49:02.528206
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '8eb46ea4e585'
down_revision: Union[str, None] = 'c6fd241b18eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
